 We recommend using tf.keras as a high-level API for building neural networks. That said, most TensorFlow APIs are usable with eager execution.

In [2]:
import tensorflow as tf
print(tf.test.is_gpu_available())

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
True


2021-09-13 14:58:06.956395: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /device:GPU:0 with 47220 MB memory:  -> device: 0, name: Quadro RTX 8000, pci bus id: 0000:67:00.0, compute capability: 7.5
2021-09-13 14:58:06.957910: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /device:GPU:1 with 47030 MB memory:  -> device: 1, name: Quadro RTX 8000, pci bus id: 0000:68:00.0, compute capability: 7.5


In [3]:
# In the tf.keras.layers package, layers are objects. To construct a layer,
# simply construct the object. Most layers take as a first argument the number
# of output dimensions / channels.
layer = tf.keras.layers.Dense(100)
# The number of input dimensions is often unnecessary, as it can be inferred
# the first time the layer is used, but it can be provided if you want to
# specify it manually, which is useful in some complex models.
layer = tf.keras.layers.Dense(10, input_shape=(None, 5))

In [4]:
# To use a layer, simply call it.
layer(tf.zeros([10, 5]))


2021-09-13 14:58:06.995765: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 47220 MB memory:  -> device: 0, name: Quadro RTX 8000, pci bus id: 0000:67:00.0, compute capability: 7.5
2021-09-13 14:58:06.996927: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 47030 MB memory:  -> device: 1, name: Quadro RTX 8000, pci bus id: 0000:68:00.0, compute capability: 7.5


<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [5]:
# Layers have many useful methods. For example, you can inspect all variables
# in a layer using `layer.variables` and trainable variables using
# `layer.trainable_variables`. In this case a fully-connected layer
# will have variables for weights and biases.
layer.variables

[<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.01534688,  0.34512436, -0.372823  , -0.2847751 , -0.61375993,
          0.23365611,  0.29695797, -0.19304237,  0.00221175, -0.44627392],
        [-0.39554936,  0.6145453 , -0.17348278, -0.21842578,  0.30425632,
         -0.6014203 ,  0.5933426 , -0.18207625,  0.35804147, -0.53580993],
        [ 0.2895925 , -0.17872494,  0.19764715,  0.18876612, -0.51273227,
          0.2713027 ,  0.62135357, -0.47663015, -0.6000725 ,  0.08501625],
        [-0.42267406, -0.3493946 , -0.35278252, -0.34475857,  0.04695481,
          0.6275155 ,  0.16112196, -0.14865443, -0.07142568, -0.6131105 ],
        [ 0.42799097,  0.47907072, -0.03189659, -0.05419332, -0.39991003,
         -0.20703214, -0.23198143,  0.23511255, -0.0358637 ,  0.01513577]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [6]:
# The variables are also accessible through nice accessors
layer.kernel, layer.bias

(<tf.Variable 'dense_1/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[-0.01534688,  0.34512436, -0.372823  , -0.2847751 , -0.61375993,
          0.23365611,  0.29695797, -0.19304237,  0.00221175, -0.44627392],
        [-0.39554936,  0.6145453 , -0.17348278, -0.21842578,  0.30425632,
         -0.6014203 ,  0.5933426 , -0.18207625,  0.35804147, -0.53580993],
        [ 0.2895925 , -0.17872494,  0.19764715,  0.18876612, -0.51273227,
          0.2713027 ,  0.62135357, -0.47663015, -0.6000725 ,  0.08501625],
        [-0.42267406, -0.3493946 , -0.35278252, -0.34475857,  0.04695481,
          0.6275155 ,  0.16112196, -0.14865443, -0.07142568, -0.6131105 ],
        [ 0.42799097,  0.47907072, -0.03189659, -0.05419332, -0.39991003,
         -0.20703214, -0.23198143,  0.23511255, -0.0358637 ,  0.01513577]],
       dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>)

# Implementing custom layers

The best way to implement your own layer is extending the tf.keras.Layer class and implementing:

1. `__init__` , where you can do all input-independent initialization
2. `build`, where you know the shapes of the input tensors and can do the rest of the initialization
3. `call`, where you do the forward computation

The best way to implement your own layer is extending the tf.keras.Layer class and implementing:

`__init__` , where you can do all input-independent initialization
`build`, where you know the shapes of the input tensors and can do the rest of the initialization
`call`, where you do the forward computation



In [7]:
class MyDenseLayer(tf.keras.layers.Layer):
    def __init__(self,num_outputs):
        super(MyDenseLayer, self).__init__()
        self.num_outputs = num_outputs
    
    def build(self, input_shape):
        self.kernel = self.add_weight("kernel", shape=[int(input_shape[-1]),self.num_outputs])
        
    def call(self,inputs):
        return tf.matmul(inputs, self.kernel)
layer = MyDenseLayer(10)




In [8]:
_ = layer(tf.zeros([10,5])) # Calling the layer `.build` it. 

In [9]:
layer.variables

[<tf.Variable 'my_dense_layer/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[ 0.0806933 , -0.4017154 , -0.6069063 , -0.5681298 ,  0.49773973,
          0.31076634, -0.12566888, -0.21063569, -0.23032513,  0.6061987 ],
        [ 0.5216983 , -0.13967675, -0.08414078,  0.3906197 ,  0.58681303,
          0.31447816,  0.55978507, -0.28450835,  0.35210836, -0.45621485],
        [ 0.37886244, -0.2424385 ,  0.42914182, -0.1308096 , -0.4745692 ,
         -0.4131187 ,  0.54800016,  0.6166344 , -0.04604906, -0.34854805],
        [ 0.12049365,  0.05217397,  0.50509113, -0.32839978, -0.06425399,
          0.05908597, -0.5702238 , -0.27301475,  0.43216723, -0.6230164 ],
        [ 0.14170712, -0.26493338,  0.19611198,  0.40088254,  0.1663934 ,
          0.21620196,  0.38526446, -0.17311695,  0.3387335 , -0.18019363]],
       dtype=float32)>]

In [10]:
print([var.name for var in layer.trainable_variables])

['my_dense_layer/kernel:0']


In [14]:
# test for convolutional networks
convlayer = tf.keras.layers.Conv2D(10,(3,3))
_ = convlayer(tf.zeros([10,32,32,3]))
convlayer.variables


[<tf.Variable 'conv2d_2/kernel:0' shape=(3, 3, 3, 10) dtype=float32, numpy=
 array([[[[ 0.08549304,  0.00463147,  0.20995446,  0.14259551,
           -0.22436622,  0.18535177,  0.22405832,  0.05308171,
            0.19166662,  0.20431288],
          [-0.20619413,  0.20676379,  0.11455102, -0.15163179,
            0.03282215,  0.04949506,  0.2218485 ,  0.21412496,
            0.13070647,  0.02548058],
          [ 0.19759716,  0.21367516, -0.06055786, -0.09299877,
           -0.00755154,  0.09653433, -0.07846721, -0.119426  ,
           -0.21250057, -0.00655372]],
 
         [[-0.16264641,  0.09843038, -0.00997697,  0.13627239,
            0.12827678, -0.09802169, -0.13522354, -0.12958649,
            0.1686626 , -0.15718603],
          [ 0.00630628, -0.05486156,  0.18916242,  0.05059217,
            0.16535331, -0.09154329,  0.13618474,  0.2094361 ,
            0.11571838, -0.14504044],
          [-0.12885422,  0.20255686,  0.18671818, -0.00268261,
            0.21465905,  0.1893395 , -

### Models: Composing layers

Many interesting layer-like things in machine learning models are implemented by composing existing layers. For example, each residual block in a resnet is a composition of convolutions, batch normalizations, and a shortcut. Layers can be nested inside other layers.

Typically you inherit from keras.Model when you need the model methods like: Model.fit,Model.evaluate, and Model.save (see Custom Keras layers and models for details).

One other feature provided by keras.Model (instead of keras.layers.Layer) is that in addition to tracking variables, a keras.Model also tracks its internal layers, making them easier to inspect.

# ResNet block:

class ResnetIdentityBlock(tf.keras.Model):
  def __init__(self, kernel_size, filters):
    super(ResnetIdentityBlock, self).__init__(name='')
    filters1, filters2, filters3 = filters

    self.conv2a = tf.keras.layers.Conv2D(filters1, (1, 1))
    self.bn2a = tf.keras.layers.BatchNormalization()

    self.conv2b = tf.keras.layers.Conv2D(filters2, kernel_size, padding='same')
    self.bn2b = tf.keras.layers.BatchNormalization()

    self.conv2c = tf.keras.layers.Conv2D(filters3, (1, 1))
    self.bn2c = tf.keras.layers.BatchNormalization()

  def call(self, input_tensor, training=False):
    x = self.conv2a(input_tensor)
    x = self.bn2a(x, training=training)
    x = tf.nn.relu(x)

    x = self.conv2b(x)
    x = self.bn2b(x, training=training)
    x = tf.nn.relu(x)

    x = self.conv2c(x)
    x = self.bn2c(x, training=training)

    x += input_tensor
    return tf.nn.relu(x)


block = ResnetIdentityBlock(1, [1, 2, 3])

_ = block(tf.zeros([1, 2, 3, 3]))

In [16]:
class ResnetIdentityBlock(tf.keras.Model):
  def __init__(self, kernel_size, filters):
    super(ResnetIdentityBlock, self).__init__(name='')
    filters1, filters2, filters3 = filters

    self.conv2a = tf.keras.layers.Conv2D(filters1, (1, 1))
    self.bn2a = tf.keras.layers.BatchNormalization()

    self.conv2b = tf.keras.layers.Conv2D(filters2, kernel_size, padding='same')
    self.bn2b = tf.keras.layers.BatchNormalization()

    self.conv2c = tf.keras.layers.Conv2D(filters3, (1, 1))
    self.bn2c = tf.keras.layers.BatchNormalization()

  def call(self, input_tensor, training=False):
    x = self.conv2a(input_tensor)
    x = self.bn2a(x, training=training)
    x = tf.nn.relu(x)

    x = self.conv2b(x)
    x = self.bn2b(x, training=training)
    x = tf.nn.relu(x)

    x = self.conv2c(x)
    x = self.bn2c(x, training=training)

    x += input_tensor
    return tf.nn.relu(x)


block = ResnetIdentityBlock(1, [1, 2, 3])

In [17]:
_ = block(tf.zeros([1, 2, 3, 3]))

In [18]:
block.layers

In [19]:
len(block.variables)

18

In [20]:
block.summary()

Model: ""
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_3 (Conv2D)            multiple                  4         
_________________________________________________________________
batch_normalization (BatchN  multiple                  4         
ormalization)                                                    
_________________________________________________________________
conv2d_4 (Conv2D)            multiple                  4         
_________________________________________________________________
batch_normalization_1 (Batc  multiple                  8         
hNormalization)                                                  
_________________________________________________________________
conv2d_5 (Conv2D)            multiple                  9         
_________________________________________________________________
batch_normalization_2 (Batc  multiple                  12        


### Much of the time, however, models which compose many layers simply call one layer after the other. This can be done in very little code using tf.keras.Sequential:

In [21]:
my_seq = tf.keras.Sequential([tf.keras.layers.Conv2D(1, (1, 1),
                                                    input_shape=(
                                                        None, None, 3)),
                             tf.keras.layers.BatchNormalization(),
                             tf.keras.layers.Conv2D(2, 1,
                                                    padding='same'),
                             tf.keras.layers.BatchNormalization(),
                             tf.keras.layers.Conv2D(3, (1, 1)),
                             tf.keras.layers.BatchNormalization()])
my_seq(tf.zeros([1, 2, 3, 3]))

<tf.Tensor: shape=(1, 2, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [22]:
my_seq.summary()


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_6 (Conv2D)            (None, None, None, 1)     4         
_________________________________________________________________
batch_normalization_3 (Batc  (None, None, None, 1)     4         
hNormalization)                                                  
_________________________________________________________________
conv2d_7 (Conv2D)            (None, None, None, 2)     4         
_________________________________________________________________
batch_normalization_4 (Batc  (None, None, None, 2)     8         
hNormalization)                                                  
_________________________________________________________________
conv2d_8 (Conv2D)            (None, None, None, 3)     9         
_________________________________________________________________
batch_normalization_5 (Batc  (None, None, None, 3)     1